# .github/workflows/check_chiikawa_stock.yml
name: Chiikawa Market Stock Checker 

on:
  schedule:
    # 定時執行：每天 UTC 時間早上 8 點運行。
    # 這是 crontab 語法：分 時 日 月 週
    # 更多資訊：https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # 例如，如果您想每 6 小時運行一次，可以是 '0 */6 * * *'
    - cron: '0 8 * * *'
  workflow_dispatch: # 允許您在 GitHub 介面手動觸發此 workflow

jobs:
  check-stock-py:
    runs-on: ubuntu-latest # 在 Ubuntu Linux 環境上運行

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 將您的程式碼下載到 GitHub Actions 執行器

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # 建議使用一個穩定的 Python 版本，例如 3.9 或 3.10

    - name: Install dependencies
      run: pip install requests beautifulsoup4 # 安裝 Python 依賴套件

    - name: Run stock checker script
      run: python check_stock_api.py # 執行您的 Python 腳本 (請確保您的 Python 檔案名是 check_stock_api.py)

